-- Simplified seed data for testing - removes user dependencies
-- Insert sample community businesses without user references
INSERT INTO community_businesses (
  business_name,
  description,
  category,
  subcategory,
  contact_email,
  contact_phone,
  website_url,
  social_media,
  address,
  city,
  state,
  zip_code,
  country,
  latitude,
  longitude,
  service_area_radius,
  business_hours,
  price_range,
  tags,
  specialties,
  logo_url,
  cover_image_url,
  gallery_images,
  status,
  is_verified,
  featured,
  featured_until,
  keywords
) VALUES

-- Stepping Dance Studio
(
  'Smooth Moves Dance Studio',
  'Premier stepping dance studio in Chicago offering classes for all skill levels. From beginners to advanced steppers, we provide a welcoming environment to learn and perfect the art of Chicago stepping. Our experienced instructors focus on technique, style, and the rich cultural heritage of stepping.',
  'fitness_sports',
  'Dance Studio',
  'info@smoothmoveschicago.com',
  '(312) 555-0100',
  'https://smoothmoveschicago.com',
  '{"facebook": "https://facebook.com/smoothmoveschicago", "instagram": "https://instagram.com/smoothmoveschicago", "youtube": "https://youtube.com/smoothmoveschicago"}',
  '2247 S Michigan Ave',
  'Chicago',
  'IL',
  '60616',
  'United States',
  41.8516,
  -87.6196,
  25,
  '{"monday": {"open": "17:00", "close": "22:00"}, "tuesday": {"open": "17:00", "close": "22:00"}, "wednesday": {"open": "17:00", "close": "22:00"}, "thursday": {"open": "17:00", "close": "22:00"}, "friday": {"open": "17:00", "close": "23:00"}, "saturday": {"open": "12:00", "close": "23:00"}, "sunday": {"open": "14:00", "close": "20:00"}}',
  '$$',
  ARRAY['chicago stepping', 'dance classes', 'partner dancing', 'group lessons', 'private instruction'],
  ARRAY['Chicago Stepping', 'Beginner Classes', 'Advanced Workshops', 'Private Lessons', 'Wedding Dance Prep'],
  'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=300',
  'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800',
  ARRAY['https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600'],
  'approved',
  true,
  true,
  '2024-03-31 23:59:59',
  ARRAY['dance', 'stepping', 'chicago', 'lessons', 'classes']
),

-- Event Photography
(
  'StepShot Photography',
  'Specializing in capturing the elegance and emotion of stepping events, competitions, and social dances. We understand the unique movements and moments that make stepping special, from the smooth glides to the intimate partner connections.',
  'event_services',
  'Photography',
  'bookings@stepshotphoto.com',
  '(773) 555-0200',
  'https://stepshotphoto.com',
  '{"instagram": "https://instagram.com/stepshotphoto", "facebook": "https://facebook.com/stepshotphoto"}',
  '4658 S Cottage Grove Ave',
  'Chicago',
  'IL',
  '60653',
  'United States',
  41.8095,
  -87.6063,
  50,
  '{"monday": {"closed": true}, "tuesday": {"open": "10:00", "close": "18:00"}, "wednesday": {"open": "10:00", "close": "18:00"}, "thursday": {"open": "10:00", "close": "18:00"}, "friday": {"open": "10:00", "close": "20:00"}, "saturday": {"open": "09:00", "close": "22:00"}, "sunday": {"open": "12:00", "close": "18:00"}}',
  '$$$',
  ARRAY['event photography', 'dance photography', 'stepping events', 'competitions', 'social events'],
  ARRAY['Stepping Events', 'Competition Photography', 'Social Dance Coverage', 'Portrait Sessions', 'Video Services'],
  'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=300',
  'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800',
  ARRAY['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600'],
  'approved',
  true,
  false,
  NULL,
  ARRAY['photography', 'events', 'stepping', 'dance', 'professional']
),

-- Formal Wear Boutique
(
  'Elegant Steps Boutique',
  'Your one-stop shop for stepping attire and formal wear. We carry everything from classic stepping outfits to modern formal wear perfect for competitions, galas, and social events. Expert alterations available.',
  'retail_shopping',
  'Formal Wear',
  'hello@elegantstepsboutique.com',
  '(312) 555-0300',
  'https://elegantstepsboutique.com',
  '{"facebook": "https://facebook.com/elegantstepsboutique", "instagram": "https://instagram.com/elegantstepsboutique"}',
  '235 S State St',
  'Chicago',
  'IL',
  '60604',
  'United States',
  41.8781,
  -87.6276,
  15,
  '{"monday": {"open": "11:00", "close": "19:00"}, "tuesday": {"open": "11:00", "close": "19:00"}, "wednesday": {"open": "11:00", "close": "19:00"}, "thursday": {"open": "11:00", "close": "20:00"}, "friday": {"open": "11:00", "close": "20:00"}, "saturday": {"open": "10:00", "close": "21:00"}, "sunday": {"open": "12:00", "close": "18:00"}}',
  '$$$',
  ARRAY['formal wear', 'stepping attire', 'alterations', 'special occasions', 'custom fitting'],
  ARRAY['Stepping Outfits', 'Formal Dresses', 'Mens Suits', 'Accessories', 'Custom Alterations'],
  'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=300',
  'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
  ARRAY['https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=600', 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=600'],
  'approved',
  false,
  true,
  '2024-04-15 23:59:59',
  ARRAY['formal', 'fashion', 'stepping', 'attire', 'boutique']
),

-- Hair & Beauty Salon
(
  'Glam & Glow Beauty Lounge',
  'Get stepping-ready with our full-service beauty treatments. Specializing in elegant updos, professional makeup, and nail art perfect for stepping events. We understand the importance of looking your best on the dance floor.',
  'beauty_personal_care',
  'Full Service Salon',
  'appointments@glamandglow.com',
  '(773) 555-0400',
  'https://glamandglowbeauty.com',
  '{"instagram": "https://instagram.com/glamandglowbeauty", "facebook": "https://facebook.com/glamandglowbeauty", "tiktok": "https://tiktok.com/@glamandglow"}',
  '6324 S Halsted St',
  'Chicago',
  'IL',
  '60621',
  'United States',
  41.7785,
  -87.6441,
  20,
  '{"monday": {"closed": true}, "tuesday": {"open": "09:00", "close": "19:00"}, "wednesday": {"open": "09:00", "close": "19:00"}, "thursday": {"open": "09:00", "close": "20:00"}, "friday": {"open": "09:00", "close": "20:00"}, "saturday": {"open": "08:00", "close": "18:00"}, "sunday": {"open": "10:00", "close": "16:00"}}',
  '$$',
  ARRAY['hair styling', 'makeup', 'nail art', 'event preparation', 'bridal services'],
  ARRAY['Event Hair Styling', 'Professional Makeup', 'Nail Art & Design', 'Bridal Packages', 'Group Services'],
  'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=300',
  'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
  ARRAY['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600', 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600'],
  'approved',
  true,
  false,
  NULL,
  ARRAY['beauty', 'salon', 'hair', 'makeup', 'nails']
),

-- DJ Services
(
  'DJ Smooth Grooves',
  'Professional DJ services specializing in stepping music and events. With an extensive collection of classic and contemporary stepping tracks, I know exactly what gets dancers moving. Available for competitions, socials, and private events.',
  'entertainment',
  'DJ Services',
  'booking@djsmoothgrooves.com',
  '(773) 555-0600',
  'https://djsmoothgrooves.com',
  '{"instagram": "https://instagram.com/djsmoothgrooves", "soundcloud": "https://soundcloud.com/djsmoothgrooves"}',
  '1455 E 53rd St',
  'Chicago',
  'IL',
  '60615',
  'United States',
  41.7993,
  -87.5903,
  100,
  '{"monday": {"open": "12:00", "close": "20:00"}, "tuesday": {"open": "12:00", "close": "20:00"}, "wednesday": {"open": "12:00", "close": "20:00"}, "thursday": {"open": "12:00", "close": "22:00"}, "friday": {"open": "12:00", "close": "02:00"}, "saturday": {"open": "12:00", "close": "02:00"}, "sunday": {"open": "14:00", "close": "20:00"}}',
  '$$$',
  ARRAY['DJ services', 'stepping music', 'event entertainment', 'sound system', 'music mixing'],
  ARRAY['Stepping Events', 'Competition DJing', 'Social Dances', 'Private Parties', 'Wedding Receptions'],
  'https://images.unsplash.com/photo-1571266028243-d220c42d2c86?w=300',
  'https://images.unsplash.com/photo-1571266028243-d220c42d2c86?w=800',
  ARRAY['https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600', 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600'],
  'approved',
  true,
  true,
  '2024-05-31 23:59:59',
  ARRAY['DJ', 'music', 'entertainment', 'stepping', 'events']
),

-- Shoe Store
(
  'Perfect Steps Shoe Emporium',
  'The premier destination for stepping shoes and dance footwear. We carry all the top brands preferred by steppers, from classic leather soles to modern comfort designs. Expert fitting and custom sole services available.',
  'retail_shopping',
  'Footwear',
  'info@perfectstepsshoes.com',
  '(773) 555-0800',
  'https://perfectstepsshoes.com',
  '{"instagram": "https://instagram.com/perfectstepsshoes"}',
  '754 E 47th St',
  'Chicago',
  'IL',
  '60653',
  'United States',
  41.8097,
  -87.6006,
  25,
  '{"monday": {"open": "10:00", "close": "19:00"}, "tuesday": {"open": "10:00", "close": "19:00"}, "wednesday": {"open": "10:00", "close": "19:00"}, "thursday": {"open": "10:00", "close": "20:00"}, "friday": {"open": "10:00", "close": "20:00"}, "saturday": {"open": "09:00", "close": "20:00"}, "sunday": {"open": "12:00", "close": "17:00"}}',
  '$$',
  ARRAY['dance shoes', 'stepping shoes', 'leather soles', 'custom fitting', 'shoe repair'],
  ARRAY['Stepping Shoes', 'Dance Footwear', 'Custom Fitting', 'Sole Replacement', 'Shoe Repair'],
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
  ARRAY['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600', 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600'],
  'approved',
  true,
  false,
  NULL,
  ARRAY['shoes', 'dance', 'stepping', 'footwear', 'retail']
);

-- Insert sample stepping classes (remove instructor_id foreign key constraint for now)
INSERT INTO stepping_classes (
  instructor_name,
  title,
  description,
  class_type,
  level,
  category,
  location_type,
  venue,
  address,
  city,
  state,
  zip_code,
  latitude,
  longitude,
  schedule_type,
  start_date,
  end_date,
  class_time,
  duration_minutes,
  days_of_week,
  price,
  capacity,
  has_rsvp,
  contact_email,
  contact_phone,
  preferred_contact,
  prerequisites,
  what_to_bring,
  extras,
  tags,
  status,
  is_active,
  is_featured
) VALUES 
-- Chicago Stepping Fundamentals
(
  'Marcus "Smooth" Johnson',
  'Chicago Stepping Fundamentals',
  'Master the art of Chicago Stepping with this comprehensive beginner course. Learn the signature smooth glide, basic six count, and essential partner connection that makes Chicago Stepping so elegant. Perfect for complete beginners or those looking to refine their fundamentals.',
  'Regular Class',
  'Beginner',
  'Stepping',
  'physical',
  'Southside Cultural Center',
  '4506 S Drexel Blvd',
  'Chicago',
  'IL',
  '60653',
  41.8154,
  -87.6054,
  'weekly',
  '2024-02-01',
  '2024-04-25',
  '19:00',
  90,
  ARRAY[4], -- Thursday
  25.00,
  20,
  true,
  'marcus.johnson@steppingworld.com',
  '(312) 555-0123',
  'email',
  'None - perfect for beginners!',
  'Comfortable flat shoes (no sneakers), water bottle, positive attitude',
  'Light refreshments provided after class. Monthly social dance included.',
  ARRAY['fundamentals', 'chicago stepping', 'beginner', 'six count', 'partner dancing'],
  'published',
  true,
  true
),

-- Advanced Footwork Workshop  
(
  'Lisa "Fancy Feet" Davis',
  'Advanced Footwork & Style Workshop',
  'Take your stepping to the next level with complex footwork patterns, styling techniques, and advanced partner dynamics. This intensive workshop focuses on musicality, creative expression, and developing your unique stepping style.',
  'Workshop',
  'Advanced',
  'Stepping',
  'physical',
  'DuSable Museum Dance Studio',
  '740 E 56th Pl',
  'Chicago',
  'IL',
  '60637',
  41.7910,
  -87.6086,
  'single',
  '2024-02-17',
  NULL,
  '14:00',
  180, -- 3 hours
  NULL,
  75.00,
  15,
  true,
  'lisa.davis@advancedstepping.com',
  '(773) 555-0456',
  'phone',
  'Must have at least 2 years of stepping experience and know basic patterns',
  'Professional dance shoes, knee pads (optional), towel',
  'Video recording available for participants. Certificate of completion provided.',
  ARRAY['advanced', 'footwork', 'workshop', 'styling', 'musicality'],
  'published',
  true,
  false
),

-- Online Virtual Class
(
  'Dr. Patricia "Step Prof" Williams',
  'Virtual Stepping Basics - Learn from Home',
  'Perfect for those who want to learn stepping from the comfort of home. Interactive online sessions with personalized feedback, downloadable practice materials, and access to our private student community.',
  'Regular Class',
  'Beginner',
  'Stepping',
  'online',
  NULL,
  NULL,
  'Online',
  'IL',
  NULL,
  NULL,
  NULL,
  'weekly',
  '2024-02-05',
  '2024-03-25',
  '20:00',
  75,
  ARRAY[1], -- Monday
  20.00,
  30,
  true,
  'patricia@virtualstepping.com',
  '(312) 555-0789',
  'email',
  'Stable internet connection, 6x6 feet of clear space',
  'Comfortable clothes, water, small towel, phone or tablet for recording',
  'Recorded sessions available for review. Private Facebook group access.',
  ARRAY['online', 'virtual', 'beginner', 'remote learning'],
  'published',
  true,
  false
),

-- Atlanta Partner Connection
(
  'Carlos "Connect" Martinez',
  'Partner Connection & Leading Mastery',
  'Focus on the most important aspect of stepping - the connection between partners. Learn proper leading and following techniques, communication through dance, and how to make any partner feel confident on the floor.',
  'Group Session',
  'Intermediate',
  'Stepping',
  'physical',
  'Atlanta Dance Academy',
  '1234 Peachtree St NE',
  'Atlanta',
  'GA',
  '30309',
  33.7490,
  -84.3880,
  'weekly',
  '2024-02-06',
  '2024-03-26',
  '18:30',
  75,
  ARRAY[2], -- Tuesday
  30.00,
  16,
  true,
  'carlos@atlantastepping.com',
  '(404) 555-0234',
  'email',
  'Basic stepping knowledge and comfort with partner dancing',
  'Dance shoes, comfortable clothing that allows movement',
  'Partner rotation included. Guest instructors monthly.',
  ARRAY['partnership', 'leading', 'following', 'intermediate', 'atlanta'],
  'published',
  true,
  true
),

-- Line Dancing Class
(
  'Stephanie "Line Queen" Thompson',
  'Urban Line Dancing Fusion',
  'Combine the smoothness of stepping with the energy of line dancing. Learn popular line dances with a stepping twist, perfect for parties, events, and building confidence on the dance floor.',
  'Regular Class',
  'Beginner',
  'Line Dancing',
  'physical',
  'Community Center South',
  '8500 S Halsted St',
  'Chicago',
  'IL',
  '60620',
  41.7370,
  -87.6441,
  'weekly',
  '2024-02-03',
  '2024-04-27',
  '16:00',
  60,
  ARRAY[6], -- Saturday
  15.00,
  25,
  true,
  'stephanie@linedancing.com',
  '(312) 555-0567',
  'email',
  'None - all levels welcome',
  'Comfortable sneakers, water bottle, towel',
  'Monthly showcase performance opportunity',
  ARRAY['line dancing', 'urban', 'fusion', 'group dance', 'beginner'],
  'published',
  true,
  false
);