-- Sample data for stepping classes system
-- This script adds realistic sample data to test the classes functionality

-- First, let's insert some sample instructors (these should be real users in auth.users)
-- Note: In production, these would be actual user accounts
-- For testing, we'll use placeholder UUIDs and update with real user IDs when available

-- Insert sample stepping classes
INSERT INTO stepping_classes (
  id,
  instructor_id,
  instructor_name,
  title,
  description,
  class_type,
  level,
  category,
  location_type,
  venue,
  address,
  city,
  state,
  zip_code,
  latitude,
  longitude,
  schedule_type,
  start_date,
  end_date,
  class_time,
  duration_minutes,
  days_of_week,
  price,
  capacity,
  has_rsvp,
  contact_email,
  contact_phone,
  preferred_contact,
  prerequisites,
  what_to_bring,
  extras,
  tags,
  status,
  is_active,
  is_featured
) VALUES 
-- Chicago Stepping Fundamentals
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000001', -- Placeholder instructor ID
  'Marcus "Smooth" Johnson',
  'Chicago Stepping Fundamentals',
  'Master the art of Chicago Stepping with this comprehensive beginner course. Learn the signature smooth glide, basic six count, and essential partner connection that makes Chicago Stepping so elegant. Perfect for complete beginners or those looking to refine their fundamentals.',
  'Regular Class',
  'Beginner',
  'Stepping',
  'physical',
  'Southside Cultural Center',
  '4506 S Drexel Blvd',
  'Chicago',
  'IL',
  '60653',
  41.8154,
  -87.6054,
  'weekly',
  '2024-02-01',
  '2024-04-25',
  '19:00',
  90,
  ARRAY[4], -- Thursday
  25.00,
  20,
  true,
  'marcus.johnson@steppingworld.com',
  '(312) 555-0123',
  'email',
  'None - perfect for beginners!',
  'Comfortable flat shoes (no sneakers), water bottle, positive attitude',
  'Light refreshments provided after class. Monthly social dance included.',
  ARRAY['fundamentals', 'chicago stepping', 'beginner', 'six count', 'partner dancing'],
  'published',
  true,
  true
),

-- Advanced Footwork Workshop  
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000002',
  'Lisa "Fancy Feet" Davis',
  'Advanced Footwork & Style Workshop',
  'Take your stepping to the next level with complex footwork patterns, styling techniques, and advanced partner dynamics. This intensive workshop focuses on musicality, creative expression, and developing your unique stepping style.',
  'Workshop',
  'Advanced',
  'Stepping',
  'physical',
  'DuSable Museum Dance Studio',
  '740 E 56th Pl',
  'Chicago',
  'IL',
  '60637',
  41.7910,
  -87.6086,
  'single',
  '2024-02-17',
  NULL,
  '14:00',
  180, -- 3 hours
  NULL,
  75.00,
  15,
  true,
  'lisa.davis@advancedstepping.com',
  '(773) 555-0456',
  'phone',
  'Must have at least 2 years of stepping experience and know basic patterns',
  'Professional dance shoes, knee pads (optional), towel',
  'Video recording available for participants. Certificate of completion provided.',
  ARRAY['advanced', 'footwork', 'workshop', 'styling', 'musicality'],
  'published',
  true,
  false
),

-- Online Virtual Class
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000003',
  'Dr. Patricia "Step Prof" Williams',
  'Virtual Stepping Basics - Learn from Home',
  'Perfect for those who want to learn stepping from the comfort of home. Interactive online sessions with personalized feedback, downloadable practice materials, and access to our private student community.',
  'Regular Class',
  'Beginner',
  'Stepping',
  'online',
  NULL,
  NULL,
  'Online',
  'IL',
  NULL,
  NULL,
  NULL,
  'weekly',
  '2024-02-05',
  '2024-03-25',
  '20:00',
  75,
  ARRAY[1], -- Monday
  20.00,
  30,
  true,
  'patricia@virtualstepping.com',
  '(312) 555-0789',
  'email',
  'Stable internet connection, 6x6 feet of clear space',
  'Comfortable clothes, water, small towel, phone or tablet for recording',
  'Recorded sessions available for review. Private Facebook group access.',
  ARRAY['online', 'virtual', 'beginner', 'remote learning'],
  'published',
  true,
  false
),

-- Atlanta Partner Connection
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000004',
  'Carlos "Connect" Martinez',
  'Partner Connection & Leading Mastery',
  'Focus on the most important aspect of stepping - the connection between partners. Learn proper leading and following techniques, communication through dance, and how to make any partner feel confident on the floor.',
  'Group Session',
  'Intermediate',
  'Stepping',
  'physical',
  'Atlanta Dance Academy',
  '1234 Peachtree St NE',
  'Atlanta',
  'GA',
  '30309',
  33.7490,
  -84.3880,
  'weekly',
  '2024-02-06',
  '2024-03-26',
  '18:30',
  75,
  ARRAY[2], -- Tuesday
  30.00,
  16,
  true,
  'carlos@atlantastepping.com',
  '(404) 555-0234',
  'email',
  'Basic stepping knowledge and comfort with partner dancing',
  'Dance shoes, comfortable clothing that allows movement',
  'Partner rotation included. Guest instructors monthly.',
  ARRAY['partnership', 'leading', 'following', 'intermediate', 'atlanta'],
  'published',
  true,
  true
),

-- Line Dancing Class
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000005',
  'Stephanie "Line Queen" Thompson',
  'Urban Line Dancing Fusion',
  'Combine the smoothness of stepping with the energy of line dancing. Learn popular line dances with a stepping twist, perfect for parties, events, and building confidence on the dance floor.',
  'Regular Class',
  'Beginner',
  'Line Dancing',
  'physical',
  'Community Center South',
  '8500 S Halsted St',
  'Chicago',
  'IL',
  '60620',
  41.7370,
  -87.6441,
  'weekly',
  '2024-02-03',
  '2024-04-27',
  '16:00',
  60,
  ARRAY[6], -- Saturday
  15.00,
  25,
  true,
  'stephanie@linedancing.com',
  '(312) 555-0567',
  'email',
  'None - all levels welcome',
  'Comfortable sneakers, water bottle, towel',
  'Monthly showcase performance opportunity',
  ARRAY['line dancing', 'urban', 'fusion', 'group dance', 'beginner'],
  'published',
  true,
  false
),

-- Health Walking Class
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000006',
  'Robert "Walker" Jackson',
  'Stepping into Wellness - Health Walking',
  'Low-impact movement class that incorporates stepping rhythms with walking patterns. Perfect for seniors or those with mobility concerns who want to stay active and connected to the stepping community.',
  'Regular Class',
  'Beginner',
  'Walking',
  'physical',
  'Millennium Park Walking Path',
  '201 E Randolph St',
  'Chicago',
  'IL',
  '60602',
  41.8826,
  -87.6233,
  'weekly',
  '2024-02-02',
  '2024-05-31',
  '10:00',
  45,
  ARRAY[5], -- Friday
  10.00,
  15,
  true,
  'robert@wellnesswalking.com',
  '(312) 555-0890',
  'phone',
  'Ability to walk for 30+ minutes',
  'Comfortable walking shoes, water, weather-appropriate clothing',
  'Indoor backup location available during winter months',
  ARRAY['health', 'wellness', 'walking', 'seniors', 'low impact'],
  'published',
  true,
  false
);

-- Insert sample class images
INSERT INTO class_images (
  class_id,
  url,
  alt_text,
  is_primary
) VALUES 
-- Images would typically be uploaded to Supabase Storage
-- These are placeholder URLs that would be replaced with actual stored images
((SELECT id FROM stepping_classes WHERE title = 'Chicago Stepping Fundamentals'), 
 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800', 
 'Couples practicing Chicago stepping fundamentals', 
 true),
((SELECT id FROM stepping_classes WHERE title = 'Advanced Footwork & Style Workshop'), 
 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800', 
 'Advanced footwork demonstration', 
 true),
((SELECT id FROM stepping_classes WHERE title = 'Virtual Stepping Basics - Learn from Home'), 
 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 
 'Online dance class setup', 
 true),
((SELECT id FROM stepping_classes WHERE title = 'Partner Connection & Leading Mastery'), 
 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800', 
 'Partner connection demonstration', 
 true),
((SELECT id FROM stepping_classes WHERE title = 'Urban Line Dancing Fusion'), 
 'https://images.unsplash.com/photo-1571266028243-d220c42d2c86?w=800', 
 'Group line dancing class', 
 true),
((SELECT id FROM stepping_classes WHERE title = 'Stepping into Wellness - Health Walking'), 
 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 
 'Wellness walking group', 
 true);

-- Insert sample attendees (using placeholder user IDs)
INSERT INTO class_attendees (
  class_id,
  user_id,
  user_name,
  user_email,
  status,
  notes
) VALUES 
-- Chicago Stepping Fundamentals attendees
((SELECT id FROM stepping_classes WHERE title = 'Chicago Stepping Fundamentals'), 
 '00000000-0000-0000-0000-100000000001', 
 'Sarah Johnson', 
 'sarah.johnson@email.com', 
 'registered',
 'Excited to learn!'),
((SELECT id FROM stepping_classes WHERE title = 'Chicago Stepping Fundamentals'), 
 '00000000-0000-0000-0000-100000000002', 
 'Michael Brown', 
 'mike.brown@email.com', 
 'interested',
 NULL),
((SELECT id FROM stepping_classes WHERE title = 'Chicago Stepping Fundamentals'), 
 '00000000-0000-0000-0000-100000000003', 
 'Jennifer Davis', 
 'jen.davis@email.com', 
 'registered',
 'First time stepping'),

-- Advanced Workshop attendees  
((SELECT id FROM stepping_classes WHERE title = 'Advanced Footwork & Style Workshop'), 
 '00000000-0000-0000-0000-100000000004', 
 'David Wilson', 
 'david.wilson@email.com', 
 'registered',
 'Been stepping for 3 years'),
((SELECT id FROM stepping_classes WHERE title = 'Advanced Footwork & Style Workshop'), 
 '00000000-0000-0000-0000-100000000005', 
 'Lisa Rodriguez', 
 'lisa.rodriguez@email.com', 
 'registered',
 'Looking to improve my style'),

-- Virtual class attendees
((SELECT id FROM stepping_classes WHERE title = 'Virtual Stepping Basics - Learn from Home'), 
 '00000000-0000-0000-0000-100000000006', 
 'Robert Taylor', 
 'robert.taylor@email.com', 
 'registered',
 'Learning during lunch breaks'),
((SELECT id FROM stepping_classes WHERE title = 'Virtual Stepping Basics - Learn from Home'), 
 '00000000-0000-0000-0000-100000000007', 
 'Maria Garcia', 
 'maria.garcia@email.com', 
 'interested',
 'Checking schedule availability');

-- This will automatically update the attendee counts due to our database triggers