#!/bin/bash

echo "Manual deployment of Square Edge Function"
echo "========================================="
echo ""
echo "To deploy the updated Square function:"
echo ""
echo "1. Go to: https://app.supabase.com/project/aszzhlgwfbijaotfddsh/functions"
echo ""
echo "2. Click on 'payments-square'"
echo ""
echo "3. Click 'Deploy function' or 'Redeploy'"
echo ""
echo "The deployment will use the latest code from your repository,"
echo "which includes the improved error handling that shows:"
echo "- Specific Square API errors"
echo "- Environment configuration details"
echo "- Whether credentials are missing"
echo ""
echo "After deployment, the errors will change from:"
echo "  'Internal server error'"
echo ""
echo "To specific errors like:"
echo "  'Square payment failed (401): UNAUTHORIZED: Invalid access token'"
echo "  'Square payment failed (404): INVALID_LOCATION: Location not found'"
echo ""
echo "This will tell us exactly what's wrong with the Square configuration."