#!/bin/bash

echo "🚀 Square Edge Function Deployment Monitor"
echo "========================================="
echo ""
echo "GitHub Actions will now deploy your edge function."
echo "This typically takes 2-3 minutes."
echo ""
echo "Monitor deployment at:"
echo "https://github.com/iradwatkins/stepper-ui-forge/actions"
echo ""
echo "Once deployed, test the improved error handling:"
echo ""
echo "1. Visit: https://www.stepperslife.com/payment-debug-test"
echo "2. Click 'Test Square Payment'"
echo "3. You should now see detailed error messages like:"
echo "   - 'Square payment failed (401): UNAUTHORIZED: The access token is invalid'"
echo "   - Environment details (production/sandbox)"
echo "   - Configuration status"
echo ""
echo "Common Square errors and fixes:"
echo "--------------------------------"
echo "• UNAUTHORIZED → Check SQUARE_ACCESS_TOKEN in Supabase dashboard"
echo "• INVALID_LOCATION → Verify SQUARE_LOCATION_ID matches your account"
echo "• SANDBOX_NOT_ALLOWED → Ensure using production credentials"
echo "• INSUFFICIENT_PERMISSIONS → Token needs payment write scope"
echo ""
echo "To check deployment status via API:"
echo "curl https://aszzhlgwfbijaotfddsh.supabase.co/functions/v1/payments-square"