name: Deploy Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          # Deploy all edge functions
          supabase functions deploy payments-paypal --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy payments-square --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy payments-cashapp --project-ref $SUPABASE_PROJECT_ID || echo "Cash App function deployment failed (expected if new)"
          supabase functions deploy payments-webhook --project-ref $SUPABASE_PROJECT_ID